---
title: "Kmeans Clustering with Iris"
author: "Sam Kavkewitz"
date: "9/30/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
library(shiny)
library(ggvis)
library(ggplot2)
library(RColorBrewer)
```


```{r ui, include=FALSE}


ui <- fluidPage(
  titlePanel("Flower Clusters"),
    sidebarPanel(
        sliderInput(
          inputId = "k",
          label = "K# of Clusters",
          min = 1,
          max = 7,
          value = 3)),
  mainPanel(
    plotOutput(
        outputId = "plot")))
    
  

```



```{r server,echo=F}
server <- function(input, output) {


  output$plot = renderPlot({
    cluster = kmeans(x = iris[,1:4],input$k,nstart=1)
    data <- cbind(iris,cluster$cluster)
    df2 <- as.data.frame(lapply(data,unlist))
    ggplot(df2,aes( x=df2$Sepal.Width, y=df2$Petal.Width,
                color= as.factor(df2$cluster), shape = df2$Species)) +
    geom_point(size = 3) + xlab("Width") + ylab("Length") +labs(colour = "K Clusters")
    
    })
}    
   
```

```{r app, echo=F}
# Create a shiny app
shinyApp(
  ui = ui,
  server = server)
```
